name: deploy

on:
  push:
    branches:
      - master

jobs:
    deploy:
      name: Deploying to Github Pages
      runs-on: ubuntu-latest
      steps:

        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            version: 16.14.2

        - name: Checkout branch
          uses: actions/checkout@v3

        - name: Install dependencies
          run: npm ci

        - name: Build
          run: npm run build

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
           github_token: ${{ secrets.ACCESS_TOKEN }}
           publish_dir: ./dist
